Products/Models/ErrorViewModel.cs
namespace Products.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Products/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace Products.Models
{
    public class Product
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Pole {nazwa} jest wymagane")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Pole {opis} jest wymagane")]
        public string Description { get; set; }
        [Required(ErrorMessage ="Pole cena jest puste. Proszę uzupełnić")]
        public decimal Price { get; set; } = 0;
    }
}

Products/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Products.Models;
using System.Diagnostics;

namespace Products.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("Home/Privacy")]
        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Redirect()
        {
            return RedirectToAction("Privacy");
        }

        [Route("test/{name}")]
        public IActionResult Product(string name)
        {
            return View();
        }

    }
}

Products/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Products.Models;

namespace Products.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Product()
        {

            Product product = new Product
            {
                Id= 1,
                Description= "Black",
                Name = "Car",
                Price = 100
            };


            return View(product); 
        }

        public IActionResult ProductList() 
        {
            var products = new List<Product>
            {
                new Product
                {
                Id= 1,
                Description= "Black",
                Name = "Car",
                Price = 100
                },
                  new Product
                {
                Id= 2,
                Description= "Apple",
                Name = "Food",
                Price = 1
                },
                    new Product
                {
                Id= 3,
                Description= "Boeing",
                Name = "Airplane",
                Price = 100000000
                },                 
            
            };
            products.Add(new Product { });
            return View(products);
        }
    
        public IActionResult Details()
        {
            ViewBag.Name = "Tomek";
            ViewData["Surname"] = "Atomek";
            TempData["SecondName"] = "Romek";

            
            return View();
        }

    
    }

}

Products/Controllers/WarehouseController.cs
using Microsoft.AspNetCore.Mvc;
using Products.Models;

namespace Products.Controllers
{
    public class WarehouseController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Add() 
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Product body)
        {
            if (!ModelState.IsValid) 
            { 
                return View(body);
            }
            return RedirectToAction("Add");
        }
    }
}

Products/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    var title = "Cześć Człowieku";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>@title</p>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Products/Views/Home/Product.cshtml
@{
    ViewData["Title"] = "Product";
}

Products/Views/Product/Details.cshtml
@{
    ViewData["Title"] = "Details";
}

<h1>Hi! see below details</h1>

<p>ViewBag: @ViewBag.Name</p>
<p>ViewData: @ViewData["Surname"]</p>
<p>TempDate: @TempData["SecondName"]</p>

Products/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Welcome to my controller product!</h1>

Products/Views/Product/Product.cshtml
@model Products.Models.Product


@{
    ViewData["Title"] = "Product";
}

<h1>Product</h1>

<p>@Model.Id</p>
<p>@Model.Name</p>
<p>@Model.Description</p>
<p>@Model.Price</p>

Products/Views/Product/ProductList.cshtml
@model IEnumerable<Products.Models.Product>
@{
    ViewData["Title"] = "ProductList";
}

<h1>ProductList</h1>

<p>
    
    @foreach (var product in Model)
    if(product.Name == "Car")
    {
            <h2>@product.Id, @product.Name, @product.Description</h2>
        }
        else
        {
        <p>We don't see other cars</p>
        }
</p>

Products/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Products</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Products.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Products</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Product">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="ProductList">Lista produktów</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Details">Szczegóły</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Warehouse" asp-action="Add">Dodaj formularz</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Products - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Products/Views/Warehouse/Add.cshtml
@model Products.Models.Product

@{
    ViewData["Title"] = "Add";
}

<h2>Dodanie formularza</h2>


@using (Html.BeginForm("Add", "Warehouse", FormMethod.Post))
{
    @Html.ValidationSummary()

    <span>Podaj imie</span>@Html.TextBoxFor(x => x.Name)
    <span>Podaj opis</span>@Html.TextBoxFor(x => x.Description)
    <span>Podaj cene</span>@Html.TextBoxFor(x => x.Price)

    <button type="submit">Zatwierdź</button>
}